# Generated by Django 2.1 on 2018-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreMascota', models.CharField(max_length=20)),
                ('Raza', models.CharField(max_length=10)),
            ],
        ),
    ]
